config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :stories
  resources :posts
  resources :users

  root "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post "/add_post", to: "users#add_post"
  get "/users/:id/posts", to: "users#posts"
  get "/users/:id/top_posts", to: "users#top_posts"
  post "/users/:id/ratings", to: "users#add_rating"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :ratings
  has_many :stories
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /add_post
  def add_post
    @post = @user.posts.build(post_params)
    if @post.save
      render json: @post, status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  # POST /users/:id/ratings
  def add_rating
    @user = User.find(params[:id])
    @post = Post.find(params[:post_id])
    @rating = Rating.new(score: params[:score], user: @user, post: @post)
    @rating.save
    render json: @rating, status: :created
  end

  # GET /users/:id/top_posts
  def top_posts
    @user = User.find(params[:id])
    @posts = @user.posts.top_rated
    render json: @posts
  end

  # GET /users/:id/posts
  def posts
    @user = User.find(params[:id])
    @posts = @user.posts
    render json: @posts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div style="padding: 10px;">
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <div style="display: flex; padding: 10px;">
    <div style="flex: 1;">
      <h1 style="color: blue;"><%= @user.username%> stories </h1>
      <% if @user.stories.length == 0 %>
        <h2> No stories yet </h2>
      <% end %>
      <% @user.stories.each do |story| %>
        <h2><%= story.title %></h2>
        <p><%= story.body %></p>
      <% end %>
      <%= link_to "Create a new story", new_story_path %>
    </div>

    <div style="flex: 1;">
      <h1 style="color: blue;"><%= @user.username%> Posts </h1>
      <% if @user.posts.length == 0 %>
        <h2> No posts yet </h2>
      <% end %>
      <% @user.posts.each do |post| %>
        <h2><%= post.title %></h2>
        <p><%= post.body %></p>
        <% if !post.ratings %>
          <h2> No ratings yet </h2>
        <% else %>
        <% post.ratings.each do |rating| %>
          <p> ----------------------- </p>
          <p>by: <%= rating.user.username %></p>
          <p><%= rating.stars %> stars</p>
          <p> => <%= rating.comment %></p>
          <p> ----------------------- </p>
        <% end %>
        <% end %>
        <% end %>
        <%= link_to "Create a new post", new_post_path %>
        <div style="margin: 10px 0;">
        <%= link_to "Add a new rating", new_rating_path %>
        </div>

  <%= button_to "Destroy this user", @user, method: :delete, style: "margin: 50px 0;" %>
</div>