config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :stories
  resources :posts
  resources :users

  root "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post "/add_post", to: "users#add_post"
  get "/users/:id/posts", to: "users#posts"
  get "/users/:id/top_posts", to: "users#top_posts"
  post "/users/:id/ratings", to: "users#add_rating"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :body, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
  <p>
    <strong>Title:</strong>
    <%= story.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= story.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= story.user_id %>
  </p>

</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Show this story", @story %> |
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stories</h1>

<div id="stories">
  <% @stories.each do |story| %>
    <%= render story %>
    <p>
      <%= link_to "Show this story", story %>
    </p>
  <% end %>
</div>

<%= link_to "New story", new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story %>

<div>
  <%= link_to "Edit this story", edit_story_path(@story) %> |
  <%= link_to "Back to stories", stories_path %>

  <%= button_to "Destroy this story", @story, method: :delete %>
</div>